language: generic 

sudo: required

services:
  - docker
  
before_install:
  - docker build -t ahasaad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahasaad/docker-react npm run test